# Generiert aus den qmake-.pro-Dateien (SOURCES). Reihenfolge wie upstream.
# Handgepflegt ergaenzt: port/ (Portierungsschicht), siehe PORT_SRCS.
PORT_SRCS := \
	port/zod_wire.cpp \
	port/zod_mapfile.cpp \
	port/zod_log.cpp \
	port/zod_pack.cpp \
  port/zod_palette.cpp \
	port/zod_schirm.cpp \
	port/zod_strings.cpp \
	port/amiga/amiga_startup.cpp \
	port/amiga/amiga_audio.cpp \
	port/amiga/video_play.cpp \

ENGINE_SRCS := $(PORT_SRCS) \
	upstream/ZodEgine_Libs/QZod_DnClientServer/qzod_dnclientserver.cpp \
	upstream/ZodEgine_Libs/QZod_DnClientServer/client_socket.cpp \
	upstream/ZodEgine_Libs/QZod_DnClientServer/server_socket.cpp \
	upstream/ZodEgine_Libs/QZod_DnClientServer/socket_handler.cpp \
	upstream/ZodEgine_Libs/QZod_DnClientServer/zbot.cpp \
	upstream/ZodEgine_Libs/QZod_DnClientServer/zbot_events.cpp \
	upstream/ZodEgine_Libs/QZod_DnClientServer/zclient.cpp \
	upstream/ZodEgine_Libs/QZod_DnClientServer/zcore.cpp \
	upstream/ZodEgine_Libs/QZod_DnClientServer/zplayer.cpp \
	upstream/ZodEgine_Libs/QZod_DnClientServer/zplayer_events.cpp \
	upstream/ZodEgine_Libs/QZod_DnClientServer/zserver.cpp \
	upstream/ZodEgine_Libs/QZod_DnClientServer/zserver_commands.cpp \
	upstream/ZodEgine_Libs/QZod_DnClientServer/zserver_events.cpp \
	upstream/ZodEgine_Libs/QZod_DnClientServer/ztray.cpp \
	upstream/ZodEgine_Libs/QZod_DnEffect/qzod_dneffect.cpp \
	upstream/ZodEgine_Libs/QZod_DnEffect/ebridgeturrent.cpp \
	upstream/ZodEgine_Libs/QZod_DnEffect/ebullet.cpp \
	upstream/ZodEgine_Libs/QZod_DnEffect/ecannondeath.cpp \
	upstream/ZodEgine_Libs/QZod_DnEffect/ecraneconco.cpp \
	upstream/ZodEgine_Libs/QZod_DnEffect/edeath.cpp \
	upstream/ZodEgine_Libs/QZod_DnEffect/edeathsparks.cpp \
	upstream/ZodEgine_Libs/QZod_DnEffect/eflame.cpp \
	upstream/ZodEgine_Libs/QZod_DnEffect/elaser.cpp \
	upstream/ZodEgine_Libs/QZod_DnEffect/elightinitfire.cpp \
	upstream/ZodEgine_Libs/QZod_DnEffect/elightrocket.cpp \
	upstream/ZodEgine_Libs/QZod_DnEffect/emapobjectturrent.cpp \
	upstream/ZodEgine_Libs/QZod_DnEffect/emissilecrockets.cpp \
	upstream/ZodEgine_Libs/QZod_DnEffect/emomissilerockets.cpp \
	upstream/ZodEgine_Libs/QZod_DnEffect/epyrofire.cpp \
	upstream/ZodEgine_Libs/QZod_DnEffect/erobotdeath.cpp \
	upstream/ZodEgine_Libs/QZod_DnEffect/erobotturrent.cpp \
	upstream/ZodEgine_Libs/QZod_DnEffect/erockparticle.cpp \
	upstream/ZodEgine_Libs/QZod_DnEffect/erockturrent.cpp \
	upstream/ZodEgine_Libs/QZod_DnEffect/esideexplosion.cpp \
	upstream/ZodEgine_Libs/QZod_DnEffect/estandard.cpp \
	upstream/ZodEgine_Libs/QZod_DnEffect/etankdirt.cpp \
	upstream/ZodEgine_Libs/QZod_DnEffect/etankoil.cpp \
	upstream/ZodEgine_Libs/QZod_DnEffect/etanksmoke.cpp \
	upstream/ZodEgine_Libs/QZod_DnEffect/etankspark.cpp \
	upstream/ZodEgine_Libs/QZod_DnEffect/etoughmushroom.cpp \
	upstream/ZodEgine_Libs/QZod_DnEffect/etoughrocket.cpp \
	upstream/ZodEgine_Libs/QZod_DnEffect/etoughsmoke.cpp \
	upstream/ZodEgine_Libs/QZod_DnEffect/etrack.cpp \
	upstream/ZodEgine_Libs/QZod_DnEffect/eturrentmissile.cpp \
	upstream/ZodEgine_Libs/QZod_DnEffect/eunitparticle.cpp \
	upstream/ZodEgine_Libs/QZod_DnEffect/qzod_effect_old.cpp \
	upstream/ZodEgine_Libs/QZod_DnGui/qzod_dngui.cpp \
	upstream/ZodEgine_Libs/QZod_DnGui/gmm_change_teams.cpp \
	upstream/ZodEgine_Libs/QZod_DnGui/gmm_main_menu.cpp \
	upstream/ZodEgine_Libs/QZod_DnGui/gmm_manage_bots.cpp \
	upstream/ZodEgine_Libs/QZod_DnGui/gmm_options.cpp \
	upstream/ZodEgine_Libs/QZod_DnGui/gmm_player_list.cpp \
	upstream/ZodEgine_Libs/QZod_DnGui/gmm_select_map.cpp \
	upstream/ZodEgine_Libs/QZod_DnGui/gmm_warning.cpp \
	upstream/ZodEgine_Libs/QZod_DnGui/zgui_main_menu_base.cpp \
	upstream/ZodEgine_Libs/QZod_DnGui/zgui_main_menu_widgets.cpp \
	upstream/ZodEgine_Libs/QZod_DnGui/gmmw_button.cpp \
	upstream/ZodEgine_Libs/QZod_DnGui/gmmw_label.cpp \
	upstream/ZodEgine_Libs/QZod_DnGui/gmmw_list.cpp \
	upstream/ZodEgine_Libs/QZod_DnGui/gmmw_radio.cpp \
	upstream/ZodEgine_Libs/QZod_DnGui/gmmw_team_color.cpp \
	upstream/ZodEgine_Libs/QZod_DnMap/qzod_dnmap.cpp \
	upstream/ZodEgine_Libs/QZod_DnMap/qzod_map.cpp \
	upstream/ZodEgine_Libs/QZod_DnMap/zmap_crater_graphics.cpp \
	upstream/ZodEgine_Libs/QZod_DnMap/zteam.cpp \
	upstream/ZodEgine_Libs/QZod_DnMap/finding/zpath_finding_old.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/qzod_dnobjects.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/cursor.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/oflag.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/ogrenades.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/ohut.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/omapobject.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/orock.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/orockets.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/zcomp_message_engine.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/zgfile.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/zgui_window.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/zhud.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/zmini_map.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/zmusic_engine.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/zobject.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/zunitrating.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/Animals/abird.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/Animals/ahutanimal.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/Buildings/bbridge.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/Buildings/bfort.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/Buildings/bradar.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/Buildings/brepair.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/Buildings/brobot.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/Buildings/bvehicle.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/Buildings/zbuilding.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/Buildings/zbuildlist.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/Cannon/cgatling.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/Cannon/cgun.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/Cannon/chowitzer.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/Cannon/cmissilecannon.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/Cannon/zcannon.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/Gw/gwcreateuser.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/Gw/gwfactory_list.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/Gw/gwlogin.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/Gw/gwproduction.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/Gw/gwproduction_fus.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/Gw/gwproduction_us.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/Robots/rgrunt.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/Robots/rlaser.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/Robots/rpsycho.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/Robots/rpyro.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/Robots/rsniper.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/Robots/rtough.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/Robots/zrobot.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/Vehicles/vapc.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/Vehicles/vcrane.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/Vehicles/vheavy.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/Vehicles/vjeep.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/Vehicles/vlight.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/Vehicles/vmedium.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/Vehicles/vmissilelauncher.cpp \
	upstream/ZodEgine_Libs/QZod_DnObjects/Vehicles/zvehicle.cpp \
	upstream/ZodEgine_Libs/QZod_DnSeparate/qzod_dnseparate.cpp \
	upstream/ZodEgine_Libs/QZod_DnSeparate/common.cpp \
	upstream/ZodEgine_Libs/QZod_DnSeparate/event_handler.cpp \
	upstream/ZodEgine_Libs/QZod_DnSeparate/SDL_rotozoom.cpp \
	upstream/ZodEgine_Libs/QZod_DnSeparate/zencrypt_aes.cpp \
	upstream/ZodEgine_Libs/QZod_DnSeparate/zfont.cpp \
	upstream/ZodEgine_Libs/QZod_DnSeparate/zfont_engine.cpp \
	upstream/ZodEgine_Libs/QZod_DnSeparate/zmysql.cpp \
	upstream/ZodEgine_Libs/QZod_DnSeparate/zpsettings.cpp \
	upstream/ZodEgine_Libs/QZod_DnSeparate/zsdl.cpp \
	upstream/ZodEgine_Libs/QZod_DnSeparate/zsdl_opengl.cpp \
	upstream/ZodEgine_Libs/QZod_DnSeparate/ztime.cpp \
	upstream/ZodEgine_Libs/QZod_DnSettings/qzod_dnsettings.cpp \
	upstream/ZodEgine_Libs/QZod_DnSettings/qzod_settings_old.cpp \
	upstream/ZodEgine_Libs/QZod_DnSoundEngine/qzod_dnsoundengine.cpp \
	upstream/ZodEgine_Libs/QZod_DnSoundEngine/qzod_soundengine_old.cpp \
	upstream/ZodEgine_Libs/QZod_DnSoundEngine/zvote.cpp \

MAIN_SRCS := \
	upstream/zod_engine/main.cpp \
	upstream/zod_engine/main_options.cpp \

# Map-Editor (P9): eigenes Binary auf denselben ENGINE_SRCS, nur mit anderer
# main(). upstream/zod_map_editor/map_editor.cpp ist toter Altstand -- es
# benutzt noch die flachen Upstream-Includes ("zmap.h" statt lib_qZod_*) und
# laesst sich gar nicht uebersetzen. Bewusst NICHT hier aufgefuehrt.
EDITOR_SRCS := \
	upstream/zod_map_editor/main.cpp \

